### ISSUE TITLE
MatIcon out of date ? (restore_from_trash)

### ISSUE THREAD

**Issue by mathieuher** [daimoonis/material-icons-font#1]
Hello,

It seems that icons are not up to date with material icons.
When I try to use <mat-icon>restore_from_trash</mat-icon> (found in the mat-icon documentation), I get the same icon as when I use <mat-icon>restore</mat-icon>.

![image](https://user-images.githubusercontent.com/32459394/63017163-e604f580-be95-11e9-9118-db53beba959f.png)

In my code :
![image](https://user-images.githubusercontent.com/32459394/63017280-3aa87080-be96-11e9-9c4e-66d8ee8b7a58.png)

Result :
![image](https://user-images.githubusercontent.com/32459394/63018267-b3a8c780-be98-11e9-8df6-5198118b39e7.png)

**Comment by daimoonis** [comment]
Thank you for your comment. The issue is that the main source repo at https://github.com/google/material-design-icons is in low maintenance mode and is not updated to same set of icons which you can see at https://material.io/resources/icons/. I will try to get some community updated content or so to be more current.

**Comment by mathieuher** [comment]
I understand the issue.
Thank you for your work and quick reply :+1: .

**Comment by daimoonis** [comment]
I made a new release as material-icons-font@2.0.0. Please give it a try.

**Comment by mathieuher** [comment]
Thank you for the quick update, it's seems to be pretty OK! :)

**Comment by johnsnelson** [comment]
Sorry to comment on an old issue, but it seems the font is outdated again and the font used by the new source repo isn't up to date either (I tried using that one directly, but it too is missing icons and this package is much easier to deploy) The icons I'm concerned with specifically are close_fullscreen and open_in_full (I like them better than fullscreen_exit and fullscreen). Since our app has to run offline I can't resort to just using the Google-hosted font and yet none of the packages I've found on github have these new icons. Is it possible for you to update this package with what's currently available from Google? If not, do you have a suggestion for getting the most up-to-date iconset? Is there anything I can do to help?

**Comment by daimoonis** [comment]
@johnsnelson Hello, thank you for comment. There seems to be an ongoing pull request at https://github.com/jossef/material-design-icons-iconfont/pull/68 which seems to incorporate the icons you are looking for. I will try to use that changes/work and update.

**Comment by daimoonis** [comment]
@johnsnelson I made a new release as material-icons-font@2.1.0. Please give it a try. In case of any additional issue please report as new issue.

**Comment by johnsnelson** [comment]
@daimoonis Thank you so much! I'll try it now.
